config/routes.rb
Tattletale::Application.routes.draw do
  resources :jobs
  resources :sessions
  resources :users

  get '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout, via: [:get, :post]

  get '/signup', to: 'users#new', as: 'signup'

  post '/jobs/:id/toggle' => 'jobs#toggle', :as => :toggle

  delete '/account/destroy' => 'users#destroy'
  get '/account' => 'users#edit', :as => :account

  get '/dashboard' => 'dashboard#index', :as => :dashboard

  match '/:url' => 'jobs#checkin', :as => :checkin, via: [:get, :post]

  root to: redirect('/dashboard')

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index
    @jobs = @user.jobs.reload

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/views/dashboard/_job.html.erb
<div id="job" class="small job <%= job.name -%> job_<%= job.status -%>">
  <h2>
    <i class="pull-left icon-<%= job.status -%>"></i>
    <%= link_to(job.name, job_path(job), :class => "show job") %>
  </h2>
  <dl class="meta">
    <dt class="description">Due in:</span>
      <dd><%= time_ago_in_words(job.next) %></dd>
    <% if job.has_checked_in? %>
      <dt class="description">Last check-in:</dt>
        <dd><%= time_ago_in_words(job.last_seen) %> ago</dd>
    <% else %>
      <dt class="description">Check-in pending</dt>
    <% end %>
  </dl>


  <!-- Split button -->
  <div class="clearfix" style="float: right">
    <div class="btn-group">
      <%= link_to('Info', job_path(job), :class => %q[btn btn-mini]) %>
      <button type="button" class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
      </button>

      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to(
            job.active? ? "Pause" : "Unpause",
            toggle_path(job),
            :method => :post,
          ) %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to(
            "Delete",
            job_path(job),
            :method => :delete,
            :class => %q[danger],
            :confirm => 'Are you sure?'
          ) %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/dashboard/_service.html.erb
<div id="service" class="service <%= service.name -%> service_<%= service.status -%>">
  <h2><%= link_to service.name, service_path(service), :class => "show service" %></h2>
  <span class="meta">
    next run: <%= service.next.strftime(date_time) %>
    <% if service.has_checked_in? %>
      | last seen <%= service.last_seen.strftime(date_time) %>
    <% else %>
      | no check-ins yet
    <% end %>
  </span>
  <span class="edit"><%= link_to 'edit', edit_service_path(service), :class => "edit" %></span>
</div>

app/views/dashboard/index.html.erb
<% if @jobs.empty? %>
  <p>
    You don't have any jobs defined.
    <%=
      link_to "Do you want to create a new job?",
        :controller => 'jobs',
        :action => 'new'
    %>
  </p>
<% else %>
  <%= render :partial => 'job', :collection => @jobs.ascending %>
<% end %>