config/routes.rb
Tattletale::Application.routes.draw do
  resources :jobs
  resources :sessions
  resources :users

  get '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout, via: [:get, :post]

  get '/signup', to: 'users#new', as: 'signup'

  post '/jobs/:id/toggle' => 'jobs#toggle', :as => :toggle

  delete '/account/destroy' => 'users#destroy'
  get '/account' => 'users#edit', :as => :account

  get '/dashboard' => 'dashboard#index', :as => :dashboard

  match '/:url' => 'jobs#checkin', :as => :checkin, via: [:get, :post]

  root to: redirect('/dashboard')

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
# frozen_string_literal: true

require "valid_email"

class User < ActiveRecord::Base
  # Each user can own many jobs
  has_many :jobs, dependent: :destroy

  # Validate that name, description, and url are set
  validates_presence_of :name, :email
  validates_uniqueness_of :name, :email, case_sensitive: false
  validates :email, email: true, if: :email?

  protected

  def self.authenticate(email)
    @user = User.find_by_email(email)
    return @user unless @user.nil?
    false
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_filter :logged_in?, only: %i[new create]
  skip_before_filter :set_user, only: %i[new create]

  def user_params
    params.require(:user).permit(:name, :email, :user)
  end
  private :user_params

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def edit
    # Nothing to see here
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html do
          session[:user_email] = @user.email
          redirect_to :root, notice: "User was successfully created."
        end
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
        are keeping this user from being created
      </h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="form">
    <div id="user_name" class="field">
      <%= f.label :name, "Your name:" %>
      <%= f.text_field :name %>
    </div>
    <div id="user_email" class="field">
      <%= f.label :email, "Your e-mail address:" %>
      <%= f.text_field :email %>
    </div>
    <div class="actions">
      <%= f.submit :class => 'submit btn btn-small login' %>
      <%
        warning = "Are you sure? If you delete " +
                  "your profile, then all tracked Jobs associated " +
                  "with your profile will also be deleted."

      %>
      <%= f.button "Delete user profile",
            :class => 'submit btn btn-small btn-danger login',
            :method => :delete,
            :confirm => warning unless @user.new_record?
      %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="user" class="user <%= @user.name -%> user_<%= @user.active -%>">
  <h2><%= @user.name %></h2>
  <span class="right">
    <%= link_to 'Edit', edit_user_path(@user) %>
  </span>
</div>

app/views/users/edit.html.erb
<div id="edit_user" class="edit user">
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<%= render :partial => 'user', :collection => @users %>

app/views/users/new.html.erb
<div id="new_user" class="new user">
  <h3>Create a new user profile</h3>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<span id="actions">
  <ul class="actions">
    <li><%= link_to("edit", edit_job_path(@user), :class => "edit") %></li>
    <li><%= link_to "delete", @user, :method => :delete, :confirm => 'Are you sure?' %></li>
  </ul>
</span>

<h3 class="user name"><%= @user.name %></h3>
<p>
  <span class="description">Email:</span> <%= @user.email %>
</p>