config/routes.rb
Tattletale::Application.routes.draw do
  resources :jobs
  resources :sessions
  resources :users

  get '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout, via: [:get, :post]

  get '/signup', to: 'users#new', as: 'signup'

  post '/jobs/:id/toggle' => 'jobs#toggle', :as => :toggle

  delete '/account/destroy' => 'users#destroy'
  get '/account' => 'users#edit', :as => :account

  get '/dashboard' => 'dashboard#index', :as => :dashboard

  match '/:url' => 'jobs#checkin', :as => :checkin, via: [:get, :post]

  root to: redirect('/dashboard')

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_footer.html.erb
<div id="footer" class="small right">
  Version: <%= Rails.configuration.version %>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <span class="logo"><%= link_to("tattletale", :root) %></span>
  <% unless @user.nil? || @user.name.nil? || @user.new_record? %>

  <!-- Split button -->
    <span class="btn-group navigation">
      <%= link_to("New job", new_job_path, :class => %q[btn btn-small]) %>
      <button type="button" class="btn btn-small dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
      </button>

      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to("User account", :account) %>
        </li>
        <li class="divider"></li>
        <li>
          <%=
            link_to(
              "Log out",
              :logout,
              :class => "logout",
              :method => :destroy
            )
          %>
        </li>
      </ul>
    </span>

  <% end %>
</div>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
  <h2 class="notice"><%= flash[:notice] %></h2>
<% end %>
<% if flash[:error] %>
  <h2 class="error"><%= flash[:error] %></h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tattletale</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <%= render "layouts/header" %>
    <div id="content">
      <%= render "layouts/notice" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </div>
</body>
</html>